/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview/national": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** National Overview */
        get: operations["national_overview_api_overview_national_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview/national/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** National Series */
        get: operations["national_series_api_overview_national_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview/national/weather": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** National Weather */
        get: operations["national_weather_api_overview_national_weather_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/city-fingerprint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** City Fingerprint */
        get: operations["city_fingerprint_api_analysis_city_fingerprint_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview Signals */
        get: operations["overview_signals_api_overview_signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coverage */
        get: operations["coverage_api_locations__location_id__coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backtest */
        get: operations["backtest_api_locations__location_id__backtest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** City Structure */
        get: operations["city_structure_api_locations__location_id__structure_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: operations["snapshot_api_locations__location_id__snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Series */
        get: operations["series_api_locations__location_id__series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecast */
        get: operations["forecast_api_locations__location_id__forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{location_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Metrics */
        get: operations["model_metrics_api_models__location_id__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{location_id}/lstm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Lstm */
        get: operations["model_lstm_api_models__location_id__lstm_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{location_id}/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Training Readiness */
        get: operations["training_readiness_api_models__location_id__readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System State */
        get: operations["system_state_api_system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Locations */
        get: operations["locations_api_locations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AirState */
        AirState: {
            /**
             * Data Kind
             * @enum {string}
             */
            data_kind: "observation" | "model_analysis";
            /** Source */
            source: string;
            /**
             * Source Time
             * Format: date-time
             */
            source_time: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Pm25 */
            pm25?: number | null;
            /** Pm10 */
            pm10?: number | null;
            /** No2 */
            no2?: number | null;
            /** O3 */
            o3?: number | null;
            /** So2 */
            so2?: number | null;
            /** Co */
            co?: number | null;
            /** Aqi */
            aqi?: number | null;
            /** Aqi Standard */
            aqi_standard?: string | null;
            /** Quality Flag */
            quality_flag: string;
            /** Station Name */
            station_name?: string | null;
            /** Metric Times */
            metric_times?: {
                [key: string]: string;
            };
            /**
             * Is Authoritative
             * @default false
             */
            is_authoritative: boolean;
        };
        /** AnalysisArtifactSummary */
        AnalysisArtifactSummary: {
            /** Run Id */
            run_id: string;
            /** Analysis Type */
            analysis_type: string;
            /** Version */
            version: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Status */
            status: string;
        };
        /** BacktestResponse */
        BacktestResponse: {
            /** Location Id */
            location_id: number;
            /** City */
            city: string;
            /** Target */
            target: string;
            /** Unit */
            unit: string;
            /** Metrics */
            metrics: components["schemas"]["ModelMetric"][];
            /** Samples */
            samples: components["schemas"]["BacktestSample"][];
        };
        /** BacktestSample */
        BacktestSample: {
            /** Model Name */
            model_name: string;
            /** Model Revision */
            model_revision: string;
            /**
             * Target At
             * Format: date-time
             */
            target_at: string;
            /** Horizon Hours */
            horizon_hours: number;
            /** Predicted Value */
            predicted_value: number;
            /** Observed Value */
            observed_value: number;
            /** Error */
            error: number;
            /** Absolute Error */
            absolute_error: number;
        };
        /** CityFingerprintMeta */
        CityFingerprintMeta: {
            /** Run Id */
            run_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /** City Count */
            city_count: number;
            /** Sample Hours Min */
            sample_hours_min: number;
            /** Sample Hours Max */
            sample_hours_max: number;
            /** Features */
            features: string[];
            /** Standardization */
            standardization: string;
            /** Local Structure Warning */
            local_structure_warning: string;
            /** Cluster Method */
            cluster_method: string;
            /** Cluster Count */
            cluster_count: number;
            /** Silhouette */
            silhouette?: number | null;
        };
        /** CityFingerprintPoint */
        CityFingerprintPoint: {
            /** Location Id */
            location_id: number;
            /** City */
            city: string;
            /** Province */
            province?: string | null;
            /** Region */
            region: string;
            /** Sample Hours */
            sample_hours: number;
            /** Cluster */
            cluster: number;
            /** Values */
            values: {
                [key: string]: number;
            };
            /** Features */
            features: {
                [key: string]: number;
            };
        };
        /** CityFingerprintResponse */
        CityFingerprintResponse: {
            meta: components["schemas"]["CityFingerprintMeta"];
            /** Explained Variance */
            explained_variance: components["schemas"]["PCAExplainedVariance"][];
            /** Loadings */
            loadings: components["schemas"]["PCALoading"][];
            /** Points */
            points: components["schemas"]["CityFingerprintPoint"][];
            /** Cluster Profiles */
            cluster_profiles: components["schemas"]["FingerprintClusterProfile"][];
        };
        /** CitySignal */
        CitySignal: {
            /** Location Id */
            location_id: number;
            /** Name */
            name: string;
            /** Delta */
            delta: number;
            /** Peak */
            peak: number;
            /**
             * Peak At
             * Format: date-time
             */
            peak_at: string;
        };
        /** CityStructureMeta */
        CityStructureMeta: {
            /** Run Id */
            run_id: string;
            /** Location Id */
            location_id: number;
            /** City */
            city: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /** Sample Count */
            sample_count: number;
            /** Input Rows */
            input_rows: number;
            /** Dropped Rows */
            dropped_rows: number;
            /** Missing Fraction */
            missing_fraction: number;
            /** Standardization */
            standardization: string;
            /** Missing Strategy */
            missing_strategy: string;
            /** Pollution Source */
            pollution_source: string;
            /** Weather Source */
            weather_source: string;
            /** Features */
            features: string[];
        };
        /** CityStructureResponse */
        CityStructureResponse: {
            meta: components["schemas"]["CityStructureMeta"];
            /** Explained Variance */
            explained_variance: components["schemas"]["PCAExplainedVariance"][];
            /** Loadings */
            loadings: components["schemas"]["PCALoading"][];
            /** Scores */
            scores: components["schemas"]["PCAScore"][];
            /** Correlation */
            correlation: components["schemas"]["CorrelationRow"][];
        };
        /** CorrelationRow */
        CorrelationRow: {
            /** Feature */
            feature: string;
            /** Values */
            values: {
                [key: string]: number;
            };
        };
        /** CoverageDay */
        CoverageDay: {
            /** Day */
            day: string;
            /** Observation Hours */
            observation_hours: number;
            /** Model Hours */
            model_hours: number;
            /** Weather Hours */
            weather_hours: number;
            /** Observation Coverage */
            observation_coverage: number;
            /** Model Coverage */
            model_coverage: number;
            /** Weather Coverage */
            weather_coverage: number;
        };
        /** CoverageResponse */
        CoverageResponse: {
            /** Location Id */
            location_id: number;
            /** City */
            city: string;
            /** Days */
            days: number;
            /** Coverage */
            coverage: components["schemas"]["CoverageDay"][];
            /** Bindings */
            bindings: components["schemas"]["TrustBinding"][];
            /** Analyses */
            analyses: components["schemas"]["AnalysisArtifactSummary"][];
        };
        /** FingerprintClusterProfile */
        FingerprintClusterProfile: {
            /** Cluster */
            cluster: number;
            /** City Count */
            city_count: number;
            /** Top Features */
            top_features: components["schemas"]["FingerprintFeatureScore"][];
        };
        /** FingerprintFeatureScore */
        FingerprintFeatureScore: {
            /** Feature */
            feature: string;
            /** Zscore */
            zscore: number;
        };
        /** ForecastPoint */
        ForecastPoint: {
            /**
             * Target At
             * Format: date-time
             */
            target_at: string;
            /** Horizon Hours */
            horizon_hours: number;
            /** Value */
            value: number;
            /** Lower Bound */
            lower_bound?: number | null;
            /** Upper Bound */
            upper_bound?: number | null;
        };
        /** ForecastResponse */
        ForecastResponse: {
            /** Location Id */
            location_id: number;
            /** City */
            city: string;
            /** Variable */
            variable: string;
            /** Unit */
            unit: string;
            /** Series */
            series: components["schemas"]["ForecastSeries"][];
        };
        /** ForecastSeries */
        ForecastSeries: {
            /** Model Name */
            model_name: string;
            /** Model Revision */
            model_revision: string;
            /**
             * Snapshot At
             * Format: date-time
             */
            snapshot_at: string;
            /** Source */
            source: string;
            /** Points */
            points: components["schemas"]["ForecastPoint"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestionRun */
        IngestionRun: {
            /** Provider */
            provider: string;
            /** Dataset */
            dataset: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Latest Source Time */
            latest_source_time?: string | null;
            /** Status */
            status: string;
            /** Message */
            message?: string | null;
            /** Error Count */
            error_count: number;
            /** Latency Seconds */
            latency_seconds?: number | null;
        };
        /** LocationSummary */
        LocationSummary: {
            /** Location Id */
            location_id: number;
            /** Name */
            name: string;
            /** City */
            city: string;
            /** Province */
            province?: string | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Timezone */
            timezone: string;
        };
        /** LstmForecastPoint */
        LstmForecastPoint: {
            /**
             * Target At
             * Format: date-time
             */
            target_at: string;
            /** Horizon Hours */
            horizon_hours: number;
            /** Value */
            value: number;
        };
        /** LstmMeta */
        LstmMeta: {
            /** Version */
            version?: string | null;
            /** Trained At */
            trained_at?: string | null;
            /**
             * Eval Basis
             * @default cams_analysis
             */
            eval_basis: string;
            /** Params */
            params: number;
            /** Epochs */
            epochs?: number | null;
        };
        /** LstmRunResponse */
        LstmRunResponse: {
            /** Location Id */
            location_id: number;
            /** City */
            city: string;
            /** Unit */
            unit: string;
            /** Hidden */
            hidden: number;
            /** Window Hours */
            window_hours: number;
            /** Replay Hours */
            replay_hours: number;
            /** Feature Names */
            feature_names: string[];
            /** Steps */
            steps: components["schemas"]["LstmStep"][];
            /** Forecast */
            forecast: components["schemas"]["LstmForecastPoint"][];
            /** Metrics */
            metrics: components["schemas"]["ModelMetric"][];
            meta: components["schemas"]["LstmMeta"];
        };
        /** LstmStep */
        LstmStep: {
            /**
             * Target At
             * Format: date-time
             */
            target_at: string;
            /** X */
            x: number[];
            /** F */
            f: number[];
            /** I */
            i: number[];
            /** O */
            o: number[];
            /** G */
            g: number[];
            /** Cell */
            cell: number[];
            /** Hidden */
            hidden: number[];
        };
        /** Meta */
        Meta: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Data Kind
             * @enum {string}
             */
            data_kind: "observation" | "model_analysis";
            /** Metric */
            metric: string;
            /** Unit */
            unit: string;
            /** Latest Source Time */
            latest_source_time?: string | null;
            /**
             * Provider Health
             * @enum {string}
             */
            provider_health: "fresh" | "stale" | "empty";
        };
        /** ModelMetric */
        ModelMetric: {
            /** Model Name */
            model_name: string;
            /** Model Revision */
            model_revision: string;
            /** Horizon Hours */
            horizon_hours: number;
            /** Samples */
            samples: number;
            /** Mae */
            mae: number;
            /** Rmse */
            rmse: number;
        };
        /** ModelMetricsResponse */
        ModelMetricsResponse: {
            /** Location Id */
            location_id: number;
            /** City */
            city: string;
            /** Target */
            target: string;
            /** Metrics */
            metrics: components["schemas"]["ModelMetric"][];
        };
        /** NationalCity */
        NationalCity: {
            /** Location Id */
            location_id: number;
            /** Name */
            name: string;
            /** Province */
            province?: string | null;
            /** Region */
            region: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Pm25 */
            pm25?: number | null;
            /** Pm25 Change 24H */
            pm25_change_24h?: number | null;
            /** China Aqi */
            china_aqi?: number | null;
            /** China Aqi Level */
            china_aqi_level?: string | null;
            /** Primary Pollutants */
            primary_pollutants?: string[];
            /** Health Effect */
            health_effect?: string | null;
            /** Advice */
            advice?: string | null;
            /** European Aqi Reference */
            european_aqi_reference?: number | null;
            /** Has Recent Ground Observation */
            has_recent_ground_observation: boolean;
            /**
             * Source Time
             * Format: date-time
             */
            source_time: string;
        };
        /** NationalOverviewResponse */
        NationalOverviewResponse: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Latest Source Time */
            latest_source_time?: string | null;
            /** Aqi Standard */
            aqi_standard: string;
            /** Aqi Semantics */
            aqi_semantics: string;
            summary: components["schemas"]["NationalSummary"];
            /** Regions */
            regions: components["schemas"]["NationalRegion"][];
            /** Cities */
            cities: components["schemas"]["NationalCity"][];
        };
        /** NationalRegion */
        NationalRegion: {
            /** Region */
            region: string;
            /** City Count */
            city_count: number;
            /** Mean Pm25 */
            mean_pm25?: number | null;
            /** Mean China Aqi */
            mean_china_aqi?: number | null;
        };
        /** NationalSeriesCity */
        NationalSeriesCity: {
            /** Location Id */
            location_id: number;
            /** Name */
            name: string;
            /** Province */
            province?: string | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Values */
            values: (number | null)[];
        };
        /** NationalSeriesResponse */
        NationalSeriesResponse: {
            /** Variable */
            variable: string;
            /** Unit */
            unit: string;
            /** Hours */
            hours: number;
            /**
             * Data Kind
             * @default model_analysis
             * @enum {string}
             */
            data_kind: "observation" | "model_analysis";
            /** Times */
            times: string[];
            /** Cities */
            cities: components["schemas"]["NationalSeriesCity"][];
        };
        /** NationalSummary */
        NationalSummary: {
            /** City Count */
            city_count: number;
            /** Model Coverage */
            model_coverage: number;
            /** Recent Ground Coverage */
            recent_ground_coverage: number;
            /** Mean Pm25 */
            mean_pm25?: number | null;
            /** High Pollution City Count */
            high_pollution_city_count: number;
            /** Worst City */
            worst_city?: string | null;
            /** Worst City Aqi */
            worst_city_aqi?: number | null;
            /** Level Counts */
            level_counts?: {
                [key: string]: number;
            };
        };
        /** NationalWeatherCity */
        NationalWeatherCity: {
            /** Location Id */
            location_id: number;
            /** Name */
            name: string;
            /** Province */
            province?: string | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Wind Speed */
            wind_speed: (number | null)[];
            /** Wind Direction */
            wind_direction: (number | null)[];
            /** Temperature */
            temperature: (number | null)[];
        };
        /** NationalWeatherResponse */
        NationalWeatherResponse: {
            /** Hours */
            hours: number;
            /** Times */
            times: string[];
            /** Cities */
            cities: components["schemas"]["NationalWeatherCity"][];
        };
        /** OverviewLocation */
        OverviewLocation: {
            /** Location Id */
            location_id: number;
            /** Name */
            name: string;
            /** Province */
            province?: string | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Value */
            value?: number | null;
            /** Aqi */
            aqi?: number | null;
            /** Dominant Pollutant */
            dominant_pollutant?: string | null;
            /** Source */
            source: string;
            /**
             * Source Time
             * Format: date-time
             */
            source_time: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Freshness Seconds */
            freshness_seconds: number;
            /** Quality Flag */
            quality_flag: string;
            /**
             * Is Authoritative
             * @default false
             */
            is_authoritative: boolean;
        };
        /** OverviewResponse */
        OverviewResponse: {
            meta: components["schemas"]["Meta"];
            /** Locations */
            locations: components["schemas"]["OverviewLocation"][];
        };
        /** OverviewSignalsResponse */
        OverviewSignalsResponse: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Basis */
            basis: string;
            /** Evaluated */
            evaluated: number;
            peak?: components["schemas"]["SignalPeak"] | null;
            /** Worsening */
            worsening?: components["schemas"]["CitySignal"][];
            /**
             * Improving Count
             * @default 0
             */
            improving_count: number;
        };
        /** PCAExplainedVariance */
        PCAExplainedVariance: {
            /** Component */
            component: string;
            /** Variance Ratio */
            variance_ratio: number;
            /** Cumulative Ratio */
            cumulative_ratio: number;
        };
        /** PCALoading */
        PCALoading: {
            /** Feature */
            feature: string;
            /** Values */
            values: {
                [key: string]: number;
            };
        };
        /** PCAScore */
        PCAScore: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Values */
            values: {
                [key: string]: number;
            };
        };
        /** ProviderBinding */
        ProviderBinding: {
            /** Location Id */
            location_id: number;
            /** City */
            city: string;
            /** Provider */
            provider: string;
            /** Station Name */
            station_name: string;
            /** External Location Id */
            external_location_id: string;
            /** Last At */
            last_at?: string | null;
            /** Active */
            active: boolean;
        };
        /** ProviderStatus */
        ProviderStatus: {
            /** Configured */
            configured: boolean;
            /**
             * State
             * @enum {string}
             */
            state: "healthy" | "stale" | "error" | "disabled" | "unknown";
            /** Last Run At */
            last_run_at?: string | null;
            /** Latest Source Time */
            latest_source_time?: string | null;
            /** Message */
            message?: string | null;
        };
        /** SeriesPoint */
        SeriesPoint: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Value */
            value: number | null;
            /** Source */
            source: string;
            /** Quality Flag */
            quality_flag: string;
        };
        /** SeriesResponse */
        SeriesResponse: {
            /** Location Id */
            location_id: number;
            /** City */
            city: string;
            /** Variable */
            variable: string;
            /** Unit */
            unit: string;
            /**
             * Data Kind
             * @enum {string}
             */
            data_kind: "observation" | "model_analysis";
            /** Points */
            points: components["schemas"]["SeriesPoint"][];
        };
        /** SignalPeak */
        SignalPeak: {
            /** Lead Hours */
            lead_hours: number;
            /**
             * Target At
             * Format: date-time
             */
            target_at: string;
            /** Value */
            value: number;
        };
        /** SnapshotResponse */
        SnapshotResponse: {
            /** Location Id */
            location_id: number;
            /** Name */
            name: string;
            /** City */
            city: string;
            /** Province */
            province: string | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            observation?: components["schemas"]["AirState"] | null;
            model_analysis?: components["schemas"]["AirState"] | null;
        };
        /** StatusResponse */
        StatusResponse: {
            /** Ok */
            ok: boolean;
            /** Storage */
            storage: string;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Providers */
            providers: {
                [key: string]: components["schemas"]["ProviderStatus"];
            };
        };
        /** SystemResponse */
        SystemResponse: {
            /** Ingestions */
            ingestions: components["schemas"]["IngestionRun"][];
            /** Bindings */
            bindings: components["schemas"]["ProviderBinding"][];
        };
        /** TrainingReadinessResponse */
        TrainingReadinessResponse: {
            /** Ready */
            ready: boolean;
            /** Location Id */
            location_id: number;
            /** City */
            city: string;
            /** Observation Rows */
            observation_rows: number;
            /** Observed Start */
            observed_start?: string | null;
            /** Observed End */
            observed_end?: string | null;
            /** Span Hours */
            span_hours: number;
            /** Completeness */
            completeness: number;
            /** Reasons */
            reasons: string[];
        };
        /** TrustBinding */
        TrustBinding: {
            /** Provider */
            provider: string;
            /** Station Name */
            station_name: string;
            /** External Location Id */
            external_location_id: string;
            /** First At */
            first_at?: string | null;
            /** Last At */
            last_at?: string | null;
            /** Active */
            active: boolean;
            /** Kind */
            kind: string;
            /** Is Authoritative */
            is_authoritative: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    national_overview_api_overview_national_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NationalOverviewResponse"];
                };
            };
        };
    };
    national_series_api_overview_national_series_get: {
        parameters: {
            query?: {
                variable?: string;
                hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NationalSeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    national_weather_api_overview_national_weather_get: {
        parameters: {
            query?: {
                hours?: number;
                location_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NationalWeatherResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    city_fingerprint_api_analysis_city_fingerprint_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityFingerprintResponse"];
                };
            };
        };
    };
    overview_signals_api_overview_signals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewSignalsResponse"];
                };
            };
        };
    };
    overview_api_overview_get: {
        parameters: {
            query?: {
                metric?: "pm25" | "pm10" | "no2" | "o3" | "so2" | "co" | "aqi" | "reference_aqi";
                data_kind?: "observation" | "model_analysis";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coverage_api_locations__location_id__coverage_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backtest_api_locations__location_id__backtest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    city_structure_api_locations__location_id__structure_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityStructureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshot_api_locations__location_id__snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    series_api_locations__location_id__series_get: {
        parameters: {
            query?: {
                variable?: "pm25" | "pm10" | "no2" | "o3" | "so2" | "co" | "aqi" | "reference_aqi";
                data_kind?: "observation" | "model_analysis";
                hours?: number;
            };
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forecast_api_locations__location_id__forecast_get: {
        parameters: {
            query?: {
                variable?: "pm25" | "pm10" | "no2" | "o3" | "so2" | "co" | "aqi" | "reference_aqi";
            };
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    model_metrics_api_models__location_id__metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelMetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    model_lstm_api_models__location_id__lstm_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LstmRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    training_readiness_api_models__location_id__readiness_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingReadinessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_state_api_system_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    locations_api_locations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationSummary"][];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
}
