/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: operations["snapshot_api_locations__location_id__snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Series */
        get: operations["series_api_locations__location_id__series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecast */
        get: operations["forecast_api_locations__location_id__forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{location_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Metrics */
        get: operations["model_metrics_api_models__location_id__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{location_id}/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Training Readiness */
        get: operations["training_readiness_api_models__location_id__readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System State */
        get: operations["system_state_api_system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Locations */
        get: operations["locations_api_locations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AirState */
        AirState: {
            /**
             * Data Kind
             * @enum {string}
             */
            data_kind: "observation" | "model_analysis";
            /** Source */
            source: string;
            /**
             * Source Time
             * Format: date-time
             */
            source_time: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Pm25 */
            pm25?: number | null;
            /** Pm10 */
            pm10?: number | null;
            /** No2 */
            no2?: number | null;
            /** O3 */
            o3?: number | null;
            /** So2 */
            so2?: number | null;
            /** Co */
            co?: number | null;
            /** Aqi */
            aqi?: number | null;
            /** Aqi Standard */
            aqi_standard?: string | null;
            /** Quality Flag */
            quality_flag: string;
            /** Station Name */
            station_name?: string | null;
            /** Metric Times */
            metric_times?: {
                [key: string]: string;
            };
            /**
             * Is Authoritative
             * @default false
             */
            is_authoritative: boolean;
        };
        /** ForecastPoint */
        ForecastPoint: {
            /**
             * Target At
             * Format: date-time
             */
            target_at: string;
            /** Horizon Hours */
            horizon_hours: number;
            /** Value */
            value: number;
            /** Lower Bound */
            lower_bound?: number | null;
            /** Upper Bound */
            upper_bound?: number | null;
        };
        /** ForecastResponse */
        ForecastResponse: {
            /** Location Id */
            location_id: number;
            /** City */
            city: string;
            /** Variable */
            variable: string;
            /** Unit */
            unit: string;
            /** Series */
            series: components["schemas"]["ForecastSeries"][];
        };
        /** ForecastSeries */
        ForecastSeries: {
            /** Model Name */
            model_name: string;
            /** Model Revision */
            model_revision: string;
            /**
             * Snapshot At
             * Format: date-time
             */
            snapshot_at: string;
            /** Source */
            source: string;
            /** Points */
            points: components["schemas"]["ForecastPoint"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestionRun */
        IngestionRun: {
            /** Provider */
            provider: string;
            /** Dataset */
            dataset: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Latest Source Time */
            latest_source_time?: string | null;
            /** Status */
            status: string;
            /** Message */
            message?: string | null;
            /** Error Count */
            error_count: number;
            /** Latency Seconds */
            latency_seconds?: number | null;
        };
        /** LocationSummary */
        LocationSummary: {
            /** Location Id */
            location_id: number;
            /** Name */
            name: string;
            /** City */
            city: string;
            /** Province */
            province?: string | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Timezone */
            timezone: string;
        };
        /** Meta */
        Meta: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Data Kind
             * @enum {string}
             */
            data_kind: "observation" | "model_analysis";
            /** Metric */
            metric: string;
            /** Unit */
            unit: string;
            /** Latest Source Time */
            latest_source_time?: string | null;
            /**
             * Provider Health
             * @enum {string}
             */
            provider_health: "fresh" | "stale" | "empty";
        };
        /** ModelMetric */
        ModelMetric: {
            /** Model Name */
            model_name: string;
            /** Model Revision */
            model_revision: string;
            /** Horizon Hours */
            horizon_hours: number;
            /** Samples */
            samples: number;
            /** Mae */
            mae: number;
            /** Rmse */
            rmse: number;
        };
        /** ModelMetricsResponse */
        ModelMetricsResponse: {
            /** Location Id */
            location_id: number;
            /** City */
            city: string;
            /** Target */
            target: string;
            /** Metrics */
            metrics: components["schemas"]["ModelMetric"][];
        };
        /** OverviewLocation */
        OverviewLocation: {
            /** Location Id */
            location_id: number;
            /** Name */
            name: string;
            /** Province */
            province?: string | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Value */
            value?: number | null;
            /** Aqi */
            aqi?: number | null;
            /** Dominant Pollutant */
            dominant_pollutant?: string | null;
            /** Source */
            source: string;
            /**
             * Source Time
             * Format: date-time
             */
            source_time: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Freshness Seconds */
            freshness_seconds: number;
            /** Quality Flag */
            quality_flag: string;
            /**
             * Is Authoritative
             * @default false
             */
            is_authoritative: boolean;
        };
        /** OverviewResponse */
        OverviewResponse: {
            meta: components["schemas"]["Meta"];
            /** Locations */
            locations: components["schemas"]["OverviewLocation"][];
        };
        /** ProviderBinding */
        ProviderBinding: {
            /** Location Id */
            location_id: number;
            /** City */
            city: string;
            /** Provider */
            provider: string;
            /** Station Name */
            station_name: string;
            /** External Location Id */
            external_location_id: string;
            /** Last At */
            last_at?: string | null;
            /** Active */
            active: boolean;
        };
        /** ProviderStatus */
        ProviderStatus: {
            /** Configured */
            configured: boolean;
            /**
             * State
             * @enum {string}
             */
            state: "healthy" | "stale" | "error" | "disabled" | "unknown";
            /** Last Run At */
            last_run_at?: string | null;
            /** Latest Source Time */
            latest_source_time?: string | null;
            /** Message */
            message?: string | null;
        };
        /** SeriesPoint */
        SeriesPoint: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Value */
            value: number | null;
            /** Source */
            source: string;
            /** Quality Flag */
            quality_flag: string;
        };
        /** SeriesResponse */
        SeriesResponse: {
            /** Location Id */
            location_id: number;
            /** City */
            city: string;
            /** Variable */
            variable: string;
            /** Unit */
            unit: string;
            /**
             * Data Kind
             * @enum {string}
             */
            data_kind: "observation" | "model_analysis";
            /** Points */
            points: components["schemas"]["SeriesPoint"][];
        };
        /** SnapshotResponse */
        SnapshotResponse: {
            /** Location Id */
            location_id: number;
            /** Name */
            name: string;
            /** City */
            city: string;
            /** Province */
            province: string | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            observation?: components["schemas"]["AirState"] | null;
            model_analysis?: components["schemas"]["AirState"] | null;
        };
        /** StatusResponse */
        StatusResponse: {
            /** Ok */
            ok: boolean;
            /** Storage */
            storage: string;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Providers */
            providers: {
                [key: string]: components["schemas"]["ProviderStatus"];
            };
        };
        /** SystemResponse */
        SystemResponse: {
            /** Ingestions */
            ingestions: components["schemas"]["IngestionRun"][];
            /** Bindings */
            bindings: components["schemas"]["ProviderBinding"][];
        };
        /** TrainingReadinessResponse */
        TrainingReadinessResponse: {
            /** Ready */
            ready: boolean;
            /** Location Id */
            location_id: number;
            /** City */
            city: string;
            /** Observation Rows */
            observation_rows: number;
            /** Observed Start */
            observed_start?: string | null;
            /** Observed End */
            observed_end?: string | null;
            /** Span Hours */
            span_hours: number;
            /** Completeness */
            completeness: number;
            /** Reasons */
            reasons: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    overview_api_overview_get: {
        parameters: {
            query?: {
                metric?: "pm25" | "pm10" | "no2" | "o3" | "aqi" | "reference_aqi";
                data_kind?: "observation" | "model_analysis";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshot_api_locations__location_id__snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    series_api_locations__location_id__series_get: {
        parameters: {
            query?: {
                variable?: "pm25" | "pm10" | "no2" | "o3" | "aqi" | "reference_aqi";
                data_kind?: "observation" | "model_analysis";
                hours?: number;
            };
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forecast_api_locations__location_id__forecast_get: {
        parameters: {
            query?: {
                variable?: "pm25" | "pm10" | "no2" | "o3" | "aqi" | "reference_aqi";
            };
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    model_metrics_api_models__location_id__metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelMetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    training_readiness_api_models__location_id__readiness_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingReadinessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_state_api_system_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    locations_api_locations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationSummary"][];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
}
